inputs:
        - https://raw.githubusercontent.com/github/gitignore/main/Global/Vim.gitignore
        - https://raw.githubusercontent.com/github/gitignore/main/Global/VisualStudioCode.gitignore
        - https://raw.githubusercontent.com/github/gitignore/main/Global/Backup.gitignore
        - https://raw.githubusercontent.com/github/gitignore/main/Global/Linux.gitignore
        - https://raw.githubusercontent.com/github/gitignore/main/Go.gitignore
